collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.07213639
  brandStrength: 0.4723404
  lightness: 0.7238783
  brandColors:
    - '#EBF1F4'
    - '#9AB590'
    - '#65885C'
    - '#5C90B4'
    - '#E0DA9B'
  rhythmicContrast: 0.9038097
typography_spectrum: 0.7617021
layout_spectrum: 0.2638298
name: BuildingSacredHeart
