layout_spectrum: 0.7851064
color:
  saturation: 0.07213639
  lightness: 0.7238783
  brandStrength: 0.488156
  brandColors:
    - '#FFFFFF'
    - '#A12643'
    - '#211D1E'
    - '#BF975C'
    - '#CFCFCF'
  rhythmicContrast: 0.9038097
typography_spectrum: 0.3297872
name: BuildingSacredHeart
